name: Build and Deploy with self-hosted Runner

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [self-hosted, builder]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Images
        run: |
          docker build -t aungkowin/my-frontend:latest ./frontend
          docker build -t aungkowin/my-backend:latest ./backend

      - name: Push Docker Images
        run: |
          docker push aungkowin/my-frontend:latest
          docker push aungkowin/my-backend:latest

      - name: Debug network to VM2
        run: |
            ping -c 3 ${{ secrets.VM2_IP }} || echo "Ping failed"
            ssh -vvv -o StrictHostKeyChecking=no -i vm2_key ko@${{ secrets.VM2_IP }} "echo Connected"
        

      - name: SSH to VM2 and Start Runner (Background)
        run: |
          echo "${{ secrets.VM2_SSH_KEY }}" > vm2_key
          chmod 600 vm2_key
          ssh -o StrictHostKeyChecking=no -i vm2_key ko@${{ secrets.VM2_IP }} '
            cd ~/actions-runner && nohup ./run.sh > runner.log 2>&1 &
          '

  deploy:
    needs: build
    runs-on: [self-hosted, deployer]

    steps:
      - name: Pull & Redeploy Containers
        run: |
          docker pull aungkowin/my-frontend:latest
          docker pull aungkowin/my-backend:latest

          docker rm -f frontend-container || true
          docker rm -f backend-container || true

          docker run -d --name frontend-container -p 80:80 aungkowin/my-frontend:latest
          docker run -d --name backend-container -p 5000:5000 aungkowin/my-backend:latest
