name: Build and Deploy with self-hosted Runner

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [self-hosted, builder]
    steps:
      - uses: actions/checkout@v3

      # ✅ Auto-run run.sh inside Builder VM
      - name: Run Builder Setup Script
        run: bash /home/aung/actions-runner/run.sh

      - name: Build Docker Images
        run: |
          docker build -t aungkowin/my-frontend:latest ./frontend
          docker build -t aungkowin/my-backend:latest ./backend

      - name: Login & Push to DockerHub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push aungkowin/my-frontend:latest
          docker push aungkowin/my-backend:latest

  deploy:
    needs: build
    runs-on: [self-hosted, builder]   # Still using builder to SSH remotely
    steps:
      # ✅ Setup SSH key for remote access
      - name: Setup SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key

      # ✅ SSH into Deployer VM and run run.sh
      - name: SSH into Deployer and Run run.sh
        run: |
          ssh -i private_key -o StrictHostKeyChecking=no ubuntu@DEPLOYER_VM_IP 'bash /home/ko/actions-runner/run.sh'

      # ✅ Redeploy Docker Containers Remotely
      - name: Pull and Run Docker Containers
        run: |
          ssh -i private_key -o StrictHostKeyChecking=no ubuntu@DEPLOYER_VM_IP << 'EOF'
            docker pull aungkowin/my-frontend:latest
            docker pull aungkowin/my-backend:latest

            docker rm -f frontend-container || true
            docker rm -f backend-container || true

            docker run -d --name frontend-container -p 80:80 aungkowin/my-frontend:latest
            docker run -d --name backend-container -p 5000:5000 aungkowin/my-backend:latest
          EOF
