name: Build and Deploy with self-hosted Runner

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [self-hosted, builder]
    steps:
      - name: Run Runner-local script
        run: /home/aung/actions-runner/run.sh

      - name: Build Docker Images
        run: |
          docker build -t aungkowin/my-frontend:latest ./frontend
          docker build -t aungkowin/my-backend:latest ./backend

      - name: Login & Push to DockerHub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push aungkowin/my-frontend:latest
          docker push aungkowin/my-backend:latest

  deploy:
    needs: build
    runs-on: [self-hosted, deployer]
    
    steps:
      - name: SSH to Deployer and Run Script
        run: |
          echo "${{ secrets.VM2_SSH_KEY }}" > vm2_key
          chmod 600 vm2_key

          ssh -o StrictHostKeyChecking=no -i vm2_key root@VM2_IP 'bash ~/run.sh'
      
          - name: Pull & Redeploy Containers
            run: |
              docker pull aungkowin/my-frontend:latest
              docker pull aungkowin/my-backend:latest

              docker rm -f frontend-container || true
              docker rm -f backend-container || true

              docker run -d --name frontend-container -p 80:80 aungkowin/my-frontend:latest
              docker run -d --name backend-container -p 5000:5000 aungkowin/my-backend:latest


      
