name: Build and Deploy with self-hosted Runner

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [self-hosted, builder]
    steps:
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Images
        run: |
          docker build -t aungkowin/my-frontend:latest ./frontend
          docker build -t aungkowin/my-backend:latest ./backend

      - name: Push to DockerHub
        run: |
          docker push aungkowin/my-frontend:latest
          docker push aungkowin/my-backend:latest

  deploy:
    needs: build
    runs-on: [self-hosted, deployer]
    steps:
      - name: Create SSH Key for VM2
        run: |
          echo "${{ secrets.VM2_SSH_KEY }}" > vm2_key
          chmod 600 vm2_key

      - name: SSH to Deployer and Run Script
        run: |
          ssh -o StrictHostKeyChecking=no -i vm2_key root@VM2_IP 'bash ~/run.sh'

      - name: Pull & Redeploy Containers
        run: |
          docker pull aungkowin/my-frontend:latest
          docker pull aungkowin/my-backend:latest

          docker rm -f frontend-container || true
          docker rm -f backend-container || true

          docker run -d --name frontend-container -p 80:80 aungkowin/my-frontend:latest
          docker run -d --name backend-container -p 5000:5000 aungkowin/my-backend:latest
