name: Build and Deploy with self-hosted Runner

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [self-hosted, builder]
    steps:
      - uses: actions/checkout@v3

      - name: Run Local Builder Setup
        run: ./run.sh

      - name: Build Docker Images
        run: |
          docker build -t aungkowin/my-frontend:latest ./frontend
          docker build -t aungkowin/my-backend:latest ./backend

      - name: Login & Push to DockerHub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push aungkowin/my-frontend:latest
          docker push aungkowin/my-backend:latest

  deploy:
    needs: build
    runs-on: [self-hosted, builder]   # still runs from builder, deploys remotely
    steps:
      - name: Setup SSH Key for Remote Access
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key

      - name: SSH into Deployer VM and Run Script
        run: |
          ssh -i private_key -o StrictHostKeyChecking=no ubuntu@DEPLOYER_VM_IP 'bash /home/ubuntu/run.sh'

      - name: SSH Pull & Redeploy Containers
        run: |
          ssh -i private_key -o StrictHostKeyChecking=no ubuntu@DEPLOYER_VM_IP << 'EOF'
            docker pull aungkowin/my-frontend:latest
            docker pull aungkowin/my-backend:latest

            docker rm -f frontend-container || true
            docker rm -f backend-container || true

            docker run -d --name frontend-container -p 80:80 aungkowin/my-frontend:latest
            docker run -d --name backend-container -p 5000:5000 aungkowin/my-backend:latest
          EOF
